
language: R
cache: packages
latex: false
fortran: false

sudo: required
warnings_are_errors: true

before_install:
  - sudo apt-get install -y libproj-dev libgeos-dev gdal-bin libgdal-dev
  

services:
 - mysql

r_packages:
  - covr

before_install:
  - mysql -u root --password="" < tests/testdb.sql 


after_success:
  - Rscript -e 'library(covr); codecov()'




  