---
title: "Database Access"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{db access}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Database interfaces
===================

You can open a `*.txt` file using Notepad, Word, Excel  or even your web browser.
Similarly you can access a database using various interfaces. 

## Interfaces to MySQL/MariaDB  

##### Web browser interfaces
 * <a href="http://scidb.mpio.orn.mpg.de/phpmyadmin/" target="_blank"> phpmyadmin </a> 

##### Database software installed locally on your PC
 * <a href="http://www.heidisql.com/" target="_blank">                                                                             HeidySQL </a>
 * <a href="https://www.mysql.de/why-mysql/windows/excel/" target="_blank">                                                        MySQL for Excel</a>       
 * <a href="https://www.mysql.de/products/workbench/"  target="_blank">                                                            MySQL Workbench</a>       
 * <a href="http://extensions.openoffice.org/en/project/mysql-connector-openofficeorg/" target="_blank">                           MySQL for OpenOffice</a>  
 * <a href="http://dev.mysql.com/doc/connectors/en/connector-odbc-examples-tools-with-access-linked-tables.html" target="_blank">  MySQL for MS Access</a>   


##### R-based interfaces
 *  sdb package. To install run `` devtools::install_git("//ds.mpio.orn.mpg.de/raw_data_kemp/GIT/sdb")  `` 
 * [RMySQL](https://cran.r-project.org/package=RMySQL)

## Interfaces for PostgreSQL

##### Web browser interfaces
* <a href="http://scidb.mpio.orn.mpg.de/phppgadmin/" target="_blank"> phppgadmin</a>


##### Database software installed locally on your PC
* <a href="http://www.heidisql.com/" target="_blank"> HeidySQL</a>
* <a href="http://www.pgadmin.org/" target="_blank"> pgadmin </a>
* <a href="http://www.openoffice.org/dba/drivers/postgresql/" target="_blank"> postgresql for OpenOffice </a> 



##### R-based interfaces
 * sdb package To install run `` devtools::install_git("//ds.mpio.orn.mpg.de/raw_data_kemp/GIT/sdb")  `` 
 * [RMySQL](https://cran.r-project.org/package=RPostgreSQL)


















